server:
  port: 8080
spring:
  datasource:
    password: Konikkurwapony1*
    username: miko
    url: jdbc:mysql://localhost:3306/sportclub?characterEncoding=utf8&&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: miko20020921@gmail.com
    password: wabh ijwx lfzj ooug
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
